Re-run yarn install process when relevant env var configuration changes
paketo-buildpacks/yarn-install pull request #179
Opened 2021-02-24 21:03 UTC by fg-j

Resolves #128  
Signed-off-by: Emily Johnson <emjohnson@vmware.com>

## Summary

## Use Cases

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.

2021-02-25 20:02 UTC, emmjohnson commented on install_process_test.go
> +			executions     []pexec.Execution
This doesn't need to be an array since we just make one call

2021-02-26 15:53 UTC, arjun024 requested changes
Could you please take a look at the comment I left? Other than that, looks great to me!

2021-02-26 15:53 UTC, arjun024 commented on install_process.go
> +	nodeEnvFile, err := createTempFileAndWriteContents([]byte(nodeEnv), "node-env")
If the purpose is to simply calculate the checksum, could you append this data to the same file to avoid redundant I/O?

2021-03-02 16:40 UTC, arjun024 requested changes
Alright final requested change :) LGTM otherwise

2021-03-02 16:40 UTC, arjun024 commented on install_process.go
>  	if err != nil {
Looks like `(*Buffer) WriteString` always returns nil. Could you please remove the error check?

2021-03-02 18:52 UTC, arjun024 approved these changes

2021-03-02 19:10 UTC, merged